class ExploreItemModel {
  // 图片资源路径配置
  static const String _imageBasePath = 'assets/images/examples';

  final String id;
  final String name;
  final String imageUrl;
  final int likeCount;
  final int viewCount;
  final int uploadImageCount; // 重要参数：图片上传几张
  final String authorName;
  final String authorAvatar;
  final DateTime createdAt;
  final List<String> tags;
  final double aspectRatio; // 添加宽高比属性来控制卡片高度
  final String description; // 详细描述
  final String prompt; // 生成提示词
  final int commentCount; // 评论数量
  final int useCount; // 使用次数
  final bool isFollowed; // 是否已关注作者

  ExploreItemModel({
    required this.id,
    required this.name,
    required this.imageUrl,
    required this.likeCount,
    required this.viewCount,
    required this.uploadImageCount, // 关键参数
    required this.authorName,
    required this.authorAvatar,
    required this.createdAt,
    this.aspectRatio = 0.75, // 默认宽高比
    this.tags = const [],
    required this.description,
    required this.prompt,
    this.commentCount = 0,
    this.useCount = 0,
    this.isFollowed = false,
  });

  // 高质量示例数据 (完全按照Nano Banana GitHub仓库顺序)
  static List<ExploreItemModel> getMockData() {
    return [
      // 例 1: 插画变手办（by @ZHO_ZHO_ZHO）
      ExploreItemModel(
        id: '1',
        name: '插画变手办',
        imageUrl: '$_imageBasePath/demo1.jpg',
        likeCount: 1580,
        viewCount: 8200,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        aspectRatio: 0.75,
        tags: ['手办', '3D', '角色', 'Blender'],
        description: '输入: 需上传一张参考图片作为生成手办的对象',
        prompt:
            '将这张照片变成角色手办。在它后面放置一个印有角色图像的盒子，盒子上有一台电脑显示Blender建模过程。在盒子前面添加一个圆形塑料底座，角色手办站在上面。如果可能的话，将场景设置在室内',
        commentCount: 45,
        useCount: 1580,
      ),
      // 例 2: 根据地图箭头生成地面视角图片（by @tokumin）
      ExploreItemModel(
        id: '2',
        name: '根据地图箭头生成地面视角图片',
        imageUrl: '$_imageBasePath/demo2.jpg',
        likeCount: 960,
        viewCount: 5400,
        uploadImageCount: 1,
        authorName: 'tokumin',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        aspectRatio: 0.6,
        tags: ['地图', 'Google Maps', '视角转换', '街景'],
        description: '输入: 需要上传一张包含红色箭头的google maps图像',
        prompt: '画出红色箭头看到的内容 / 从红色圆圈沿箭头方向画出真实世界的视角',
        commentCount: 28,
        useCount: 960,
      ),
      // 例 3: 真实世界的AR信息化（by @bilawalsidhu）
      ExploreItemModel(
        id: '3',
        name: '真实世界的AR信息化',
        imageUrl: '$_imageBasePath/demo3.jpg',
        likeCount: 745,
        viewCount: 4100,
        uploadImageCount: 1,
        authorName: 'bilawalsidhu',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        aspectRatio: 0.8,
        tags: ['AR', 'POI', '位置', '信息化'],
        description: '输入: 需上传一张参考图像',
        prompt: '你是一个基于位置的AR体验生成器。在这张图像中突出显示[兴趣点]并标注相关信息',
        commentCount: 32,
        useCount: 745,
      ),
      // 例 4: 分离出3D建筑/制作等距模型（by @Zieeett）
      ExploreItemModel(
        id: '4',
        name: '分离出3D建筑/制作等距模型',
        imageUrl: '$_imageBasePath/demo4.jpg',
        likeCount: 1240,
        viewCount: 6800,
        uploadImageCount: 1,
        authorName: 'Zieeett',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        aspectRatio: 1.0,
        tags: ['建筑', '3D', '等距', '分离'],
        description: '输入: 需上传一张包含对应物体的图像',
        prompt: '将图像制作成白天和等距视图[仅限建筑]',
        commentCount: 41,
        useCount: 1240,
      ),
      // 例 5: 不同时代自己的照片（by @AmirMushich）
      ExploreItemModel(
        id: '5',
        name: '不同时代自己的照片',
        imageUrl: '$_imageBasePath/demo5.jpg',
        likeCount: 892,
        viewCount: 4950,
        uploadImageCount: 1,
        authorName: 'AmirMushich',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(hours: 15)),
        aspectRatio: 0.7,
        tags: ['复古', '时代', '风格', '人像'],
        description: '输入: 需上传一张人物的照片',
        prompt:
            '将角色的风格改为[1970]年代的经典[男性]风格 添加[长卷发]， [长胡子]， 将背景改为标志性的[加州夏季风景] 不要改变角色的面部',
        commentCount: 36,
        useCount: 892,
      ),
      // 例 6: 多参考图像生成（by @MrDavids1）
      ExploreItemModel(
        id: '6',
        name: '多参考图像生成',
        imageUrl: '$_imageBasePath/demo6.jpg',
        likeCount: 1680,
        viewCount: 9200,
        uploadImageCount: 4,
        authorName: 'MrDavids1',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        aspectRatio: 0.65,
        tags: ['合成', '多图', '场景', '创意'],
        description: '输入: 需上传多个参考图',
        prompt:
            '一个模特摆姿势靠在粉色宝马车上。她穿着以下物品，场景背景是浅灰色。绿色外星人是一个钥匙扣，挂在粉色手提包上。模特肩上还有一只粉色鹦鹉。旁边坐着一只戴着粉色项圈和金色耳机的哈巴狗',
        commentCount: 58,
        useCount: 1680,
      ),
      ExploreItemModel(
        id: '7',
        name: '自动修图',
        imageUrl: '$_imageBasePath/demo7.jpg',
        likeCount: 2100,
        viewCount: 11500,
        uploadImageCount: 1,
        authorName: 'op7418',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
        aspectRatio: 0.8,
        tags: ['修图', '增强', '自动', '优化'],
        description: '输入: 需上传一张需要进行修正的图像',
        prompt: '这张照片很无聊很平淡。增强它！增加对比度，提升色彩，改善光线使其更丰富，你可以裁剪和删除影响构图的细节',
        commentCount: 72,
        useCount: 2100,
      ),
      // 例 8: 手绘图控制多角色姿态（by @op7418）
      ExploreItemModel(
        id: '8',
        name: '手绘图控制多角色姿态',
        imageUrl: '$_imageBasePath/demo8.jpg',
        likeCount: 1450,
        viewCount: 8100,
        uploadImageCount: 3,
        authorName: 'op7418',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        aspectRatio: 0.56,
        tags: ['姿态', '多角色', '战斗', '控制'],
        description: '输入: 需上传角色的图像以及手绘草图',
        prompt: '让这两个角色使用图3的姿势进行战斗。添加适当的视觉背景和场景互动，生成图像比例为16:9',
        commentCount: 54,
        useCount: 1450,
      ),
      // 例 9: 跨视角图像生成（by @op7418）
      ExploreItemModel(
        id: '9',
        name: '跨视角图像生成',
        imageUrl: '$_imageBasePath/demo9.jpg',
        likeCount: 890,
        viewCount: 4800,
        uploadImageCount: 1,
        authorName: 'op7418',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
        aspectRatio: 0.75,
        tags: ['视角', '俯视', '转换', '标记'],
        description: '输入: 需上传一张地面上拍摄的照片',
        prompt: '将照片转换为俯视角度并标记摄影师的位置',
        commentCount: 32,
        useCount: 890,
      ),
      // 例 10: 定制人物贴纸（by @op7418）
      ExploreItemModel(
        id: '10',
        name: '定制人物贴纸',
        imageUrl: '$_imageBasePath/demo10.jpg',
        likeCount: 1120,
        viewCount: 6200,
        uploadImageCount: 2,
        authorName: 'op7418',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        aspectRatio: 1.0,
        tags: ['贴纸', '轮廓', '网页', '插画'],
        description: '输入: 需上传一张贴纸参考图以及一张人物图像',
        prompt: '帮我将角色变成类似图2的白色轮廓贴纸。角色需要转换成网页插画风格，并添加一个描述图1的俏皮白色轮廓短语',
        commentCount: 45,
        useCount: 1120,
      ),
      ExploreItemModel(
        id: '11',
        name: '动漫转真人Coser',
        imageUrl: '$_imageBasePath/demo11.jpg',
        likeCount: 2380,
        viewCount: 12800,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 6)),
        aspectRatio: 0.67,
        tags: ['Coser', '动漫', 'Comiket', '真人'],
        description: '输入: 需上传一张插画图像',
        prompt: '生成一个女孩cosplay这张插画的照片，背景设置在Comiket',
        commentCount: 89,
        useCount: 2380,
      ),
      ExploreItemModel(
        id: '12',
        name: '生成角色设定',
        imageUrl: '$_imageBasePath/demo12.jpg',
        likeCount: 1680,
        viewCount: 9400,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        aspectRatio: 0.6,
        tags: ['角色', '设定', '三视图', '表情'],
        description: '输入: 需上传一张角色参考图像',
        prompt:
            '为我生成人物的角色设定（Character Design） 比例设定（不同身高对比、头身比等） 三视图（正面、侧面、背面） 表情设定（Expression Sheet） → 就是你发的那种图 动作设定（Pose Sheet） → 各种常见姿势 服装设定（Costume Design）',
        commentCount: 76,
        useCount: 1680,
      ),
      ExploreItemModel(
        id: '13',
        name: '色卡线稿上色',
        imageUrl: '$_imageBasePath/demo13.jpg',
        likeCount: 1340,
        viewCount: 7600,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 8)),
        aspectRatio: 0.8,
        tags: ['上色', '线稿', '色卡', '精确'],
        description: '输入: 需上传一张线稿图和一张色卡图',
        prompt: '准确使用图2色卡为图1人物上色',
        commentCount: 52,
        useCount: 1340,
      ),
      ExploreItemModel(
        id: '14',
        name: '文章信息图',
        imageUrl: '$_imageBasePath/demo14.jpg',
        likeCount: 980,
        viewCount: 5400,
        uploadImageCount: 1,
        authorName: '黄建同学',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        aspectRatio: 0.7,
        tags: ['信息图', '文章', '卡通', '英文'],
        description: '输入: 需上传一段博客/文章',
        prompt:
            '为文章内容生成信息图 要求： 1. 将内容翻译成英文，并提炼文章的关键信息 2. 图中内容保持精简，只保留大标题 3. 图中文字采用英文 4. 加上丰富可爱的卡通人物和元素',
        commentCount: 35,
        useCount: 980,
      ),
      ExploreItemModel(
        id: '15',
        name: '更换多种发型',
        imageUrl: '$_imageBasePath/demo15.jpg',
        likeCount: 1890,
        viewCount: 10200,
        uploadImageCount: 1,
        authorName: 'balconychy',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 5, hours: 12)),
        aspectRatio: 1.0,
        tags: ['发型', '九宫格', '变换', '头像'],
        description: '输入: 需上传一张需要更换发型的人像图片',
        prompt: '以九宫格的方式生成这个人不同发型的头像',
        commentCount: 68,
        useCount: 1890,
      ),
      // 例 16: 模型标注讲解图（by @berryxia_ai）
      ExploreItemModel(
        id: '16',
        name: '模型标注讲解图',
        imageUrl: '$_imageBasePath/demo16.jpg',
        likeCount: 1240,
        viewCount: 6800,
        uploadImageCount: 0,
        authorName: 'berryxia_ai',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        aspectRatio: 0.8,
        tags: ['模型', '标注', '学术', '讲解'],
        description: '无需输入图片。绘制3D模型用于学术展示，进行标注讲解',
        prompt:
            '绘制[3D人体器官模型展示示例心脏]用于学术展示，进行标注讲解，适用于展示其原理和[每个器官]的功能，非常逼真，高度还原，精细度非常细致的设计',
        commentCount: 45,
        useCount: 1240,
      ),
      // 例 17: 定制大理石雕塑（by @umesh_ai）
      ExploreItemModel(
        id: '17',
        name: '定制大理石雕塑',
        imageUrl: '$_imageBasePath/demo17.jpg',
        likeCount: 1580,
        viewCount: 8700,
        uploadImageCount: 1,
        authorName: 'umesh_ai',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 8)),
        aspectRatio: 0.8,
        tags: ['大理石', '雕塑', '艺术', '精美'],
        description: '输入: 需上传一张参考图像',
        prompt:
            '一张超详细的图像中主体雕塑的写实图像，由闪亮的大理石制成。雕塑应展示光滑反光的大理石表面，强调其光泽和艺术工艺。设计优雅，突出大理石的美丽和深度。图像中的光线应增强雕塑的轮廓和纹理，创造出视觉上令人惊叹和迷人的效果',
        commentCount: 62,
        useCount: 1580,
      ),
      ExploreItemModel(
        id: '18',
        name: '根据食材做菜',
        imageUrl: '$_imageBasePath/demo18.jpg',
        likeCount: 1320,
        viewCount: 7200,
        uploadImageCount: 1,
        authorName: 'Gdgtify',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        aspectRatio: 0.8,
        tags: ['食材', '烹饪', '午餐', '美食'],
        description: '输入: 需上传一张带有多种食材的照片',
        prompt: '用这些食材为我做一顿美味的午餐，放在盘子里，盘子的特写视图，移除其他盘子和食材',
        commentCount: 54,
        useCount: 1320,
      ),
      ExploreItemModel(
        id: '19',
        name: '数学题推理',
        imageUrl: '$_imageBasePath/demo19.jpg',
        likeCount: 890,
        viewCount: 4800,
        uploadImageCount: 1,
        authorName: 'Gorden Sun',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 7, hours: 6)),
        aspectRatio: 0.7,
        tags: ['数学', '推理', '解题', '答案'],
        description: '输入: 需上传一道数学类的题目',
        prompt: '根据问题将问题的答案写在对应的位置上',
        commentCount: 32,
        useCount: 890,
      ),
      ExploreItemModel(
        id: '20',
        name: '旧照片上色',
        imageUrl: '$_imageBasePath/demo20.jpg',
        likeCount: 1240,
        viewCount: 6800,
        uploadImageCount: 1,
        authorName: 'GeminiApp',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        aspectRatio: 0.8,
        tags: ['修复', '上色', '旧照片', '复原'],
        description: '输入: 需上传一张老旧、需要修复的照片',
        prompt: '修复并为这张照片上色',
        commentCount: 45,
        useCount: 1240,
      ),
      ExploreItemModel(
        id: '21',
        name: 'OOTD穿搭',
        imageUrl: '$_imageBasePath/demo21.jpg',
        likeCount: 1890,
        viewCount: 10200,
        uploadImageCount: 2,
        authorName: '302.AI',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 8, hours: 12)),
        aspectRatio: 0.8,
        tags: ['穿搭', 'OOTD', '时尚', '换装'],
        description: '输入: 需上传一张人物图片和服装图片',
        prompt:
            '选择图1中的人，让他们穿上图2中的所有服装和配饰。在户外拍摄一系列写实的OOTD风格照片，使用自然光线，时尚的街头风格，清晰的全身镜头。保持图1中人物的身份和姿势，但以连贯时尚的方式展示图2中的完整服装和配饰',
        commentCount: 67,
        useCount: 1890,
      ),
      ExploreItemModel(
        id: '22',
        name: '人物换衣',
        imageUrl: '$_imageBasePath/demo22.jpg',
        likeCount: 1650,
        viewCount: 9100,
        uploadImageCount: 2,
        authorName: 'skirano',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        aspectRatio: 0.8,
        tags: ['换衣', '服装', '替换', '真实'],
        description: '输入: 需上传人物图像和衣服图像',
        prompt:
            '将输入图像中人物的服装替换为参考图像中显示的目标服装。保持人物的姿势、面部表情、背景和整体真实感不变。让新服装看起来自然、合身，并与光线和阴影保持一致。不要改变人物的身份或环境——只改变衣服',
        commentCount: 58,
        useCount: 1650,
      ),
      ExploreItemModel(
        id: '23',
        name: '多视图结果生成',
        imageUrl: '$_imageBasePath/demo23.jpg',
        likeCount: 1480,
        viewCount: 8200,
        uploadImageCount: 1,
        authorName: 'Error_HTTP_404',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 9, hours: 8)),
        aspectRatio: 0.8,
        tags: ['多视图', '三维', '透视', '全方位'],
        description: '输入: 需上传参考图像',
        prompt: '在白色背景上生成前、后、左、右、上、下视图。均匀分布。一致的主体。等距透视等效',
        commentCount: 42,
        useCount: 1480,
      ),
      ExploreItemModel(
        id: '24',
        name: '电影分镜',
        imageUrl: '$_imageBasePath/demo24.jpg',
        likeCount: 2340,
        viewCount: 12800,
        uploadImageCount: 1,
        authorName: 'GeminiApp',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        aspectRatio: 0.5,
        tags: ['电影', '分镜', '故事', '黑色电影'],
        description: '输入: 需上传参考图像',
        prompt:
            '用这两个角色创作一个令人上瘾的12部分故事，包含12张图像，讲述经典的黑色电影侦探故事。故事关于他们寻找线索并最终发现的失落的宝藏。整个故事充满刺激，有情感的高潮和低谷，以精彩的转折和高潮结尾。不要在图像中包含任何文字或文本，纯粹通过图像本身讲述故事',
        commentCount: 98,
        useCount: 2340,
      ),
      ExploreItemModel(
        id: '25',
        name: '人物姿势修改',
        imageUrl: '$_imageBasePath/demo25.jpg',
        likeCount: 1420,
        viewCount: 7800,
        uploadImageCount: 1,
        authorName: 'arrakis_ai',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 10, hours: 12)),
        aspectRatio: 0.8,
        tags: ['姿势', '修改', '视角', '调整'],
        description: '输入: 需上传参考图像',
        prompt: '让图片中的人直视前方',
        commentCount: 52,
        useCount: 1420,
      ),
      ExploreItemModel(
        id: '26',
        name: '线稿图生成图像',
        imageUrl: '$_imageBasePath/demo26.jpg',
        likeCount: 1320,
        viewCount: 7400,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        aspectRatio: 0.8,
        tags: ['线稿', '姿势', '人物', '摄影'],
        description: '输入: 需上传线稿图和参考图像',
        prompt: '将图一人物换成图二姿势，专业摄影棚拍摄',
        commentCount: 54,
        useCount: 1320,
      ),
      ExploreItemModel(
        id: '27',
        name: '为图像添加水印',
        imageUrl: '$_imageBasePath/demo27.jpg',
        likeCount: 890,
        viewCount: 4800,
        uploadImageCount: 1,
        authorName: 'AiMachete',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 11, hours: 8)),
        aspectRatio: 0.8,
        tags: ['水印', '覆盖', '文字', '标记'],
        description: '输入: 需上传参考图像',
        prompt: '在整个图片上反复覆盖"TRUMP"这个词',
        commentCount: 32,
        useCount: 890,
      ),
      ExploreItemModel(
        id: '28',
        name: '知识推理生成图像',
        imageUrl: '$_imageBasePath/demo28.jpg',
        likeCount: 1240,
        viewCount: 6800,
        uploadImageCount: 0,
        authorName: 'icreatelife',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        aspectRatio: 0.7,
        tags: ['知识', '推理', '信息图', '教育'],
        description: '无需输入图片',
        prompt: '为我制作一张世界五座最高建筑的信息图 / 制作一张关于地球上最甜蜜事物的彩色信息图',
        commentCount: 45,
        useCount: 1240,
      ),
      ExploreItemModel(
        id: '29',
        name: '红笔批注',
        imageUrl: '$_imageBasePath/demo29.jpg',
        likeCount: 1120,
        viewCount: 6200,
        uploadImageCount: 1,
        authorName: 'AiMachete',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 12, hours: 6)),
        aspectRatio: 0.8,
        tags: ['批注', '分析', '红笔', '改进'],
        description: '输入: 需上传参考图像',
        prompt: '分析这张图片。用红笔标出你可以改进的地方',
        commentCount: 38,
        useCount: 1120,
      ),
      ExploreItemModel(
        id: '30',
        name: '爆炸的食物',
        imageUrl: '$_imageBasePath/demo30.jpg',
        likeCount: 1890,
        viewCount: 10300,
        uploadImageCount: 1,
        authorName: 'icreatelife',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
        aspectRatio: 0.8,
        tags: ['食物', '爆炸', '特效', '创意'],
        description: '输入: 需上传一张食物图片',
        prompt: '让这个食物爆炸并展示其所有成分',
        commentCount: 67,
        useCount: 1890,
      ),
      ExploreItemModel(
        id: '31',
        name: '制作漫画书',
        imageUrl: '$_imageBasePath/demo31.jpg',
        likeCount: 1580,
        viewCount: 8600,
        uploadImageCount: 1,
        authorName: 'icreatelife',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 13, hours: 12)),
        aspectRatio: 0.7,
        tags: ['漫画', '漫画书', '故事', '分镜'],
        description: '输入: 需上传一张参考图像',
        prompt: '制作一本漫画书，讲述这个角色的故事',
        commentCount: 58,
        useCount: 1580,
      ),
      ExploreItemModel(
        id: '32',
        name: '动作人偶',
        imageUrl: '$_imageBasePath/demo32.jpg',
        likeCount: 1340,
        viewCount: 7400,
        uploadImageCount: 1,
        authorName: 'icreatelife',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
        aspectRatio: 0.8,
        tags: ['人偶', '动作', '手办', '可动'],
        description: '输入: 需上传一张参考图像',
        prompt: '制作这个角色的动作人偶，配有各种配件和可动关节',
        commentCount: 52,
        useCount: 1340,
      ),
      ExploreItemModel(
        id: '33',
        name: '地图生成等距建筑',
        imageUrl: '$_imageBasePath/demo33.jpg',
        likeCount: 2120,
        viewCount: 11600,
        uploadImageCount: 1,
        authorName: 'demishassabis',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 14, hours: 8)),
        aspectRatio: 1.0,
        tags: ['地图', '等距', '建筑', '3D'],
        description: '输入: 需上传一张地图图像',
        prompt: '根据这张地图创建一个等距3D建筑视图',
        commentCount: 78,
        useCount: 2120,
      ),
      ExploreItemModel(
        id: '34',
        name: '参考图控制人物表情',
        imageUrl: '$_imageBasePath/demo34.jpg',
        likeCount: 1890,
        viewCount: 10300,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        aspectRatio: 0.8,
        tags: ['表情', '控制', '人物', '参考'],
        description: '输入: 需上传人物图像和表情参考图',
        prompt: '让图1中的人物做出图2中的表情',
        commentCount: 72,
        useCount: 1890,
      ),
      ExploreItemModel(
        id: '35',
        name: '插画绘画过程四格',
        imageUrl: '$_imageBasePath/demo35.jpg',
        likeCount: 1650,
        viewCount: 9100,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 15, hours: 6)),
        aspectRatio: 0.5,
        tags: ['插画', '绘画', '过程', '四格'],
        description: '输入: 需上传一张参考图像',
        prompt: '展示这张插画的绘画过程，分为四个步骤：线稿、基础色彩、细节渲染、最终完成',
        commentCount: 68,
        useCount: 1650,
      ),
      ExploreItemModel(
        id: '36',
        name: '虚拟试妆',
        imageUrl: '$_imageBasePath/demo36.jpg',
        likeCount: 2120,
        viewCount: 11600,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 16)),
        aspectRatio: 0.8,
        tags: ['试妆', '虚拟', '美妆', '化妆'],
        description: '输入: 需上传人物图像和妆容参考图',
        prompt: '为图1中的人物化上图2中的妆容',
        commentCount: 85,
        useCount: 2120,
      ),
      ExploreItemModel(
        id: '37',
        name: '妆面分析',
        imageUrl: '$_imageBasePath/demo37.jpg',
        likeCount: 1560,
        viewCount: 8700,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 16, hours: 12)),
        aspectRatio: 0.8,
        tags: ['妆面', '分析', '美妆', '教程'],
        description: '输入: 需上传一张妆容图片',
        prompt: '分析这个妆容，详细说明使用的化妆品类型、步骤和技巧',
        commentCount: 63,
        useCount: 1560,
      ),
      ExploreItemModel(
        id: '38',
        name: '地图视角下的中土世界',
        imageUrl: '$_imageBasePath/demo38.jpg',
        likeCount: 2340,
        viewCount: 12800,
        uploadImageCount: 0,
        authorName: 'TechHallo',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 17)),
        aspectRatio: 0.7,
        tags: ['地图', '中土世界', 'Google', '奇幻'],
        description: '无需输入图片',
        prompt: '创建一张Google地图风格的中土世界地图，包含所有重要地点和路线',
        commentCount: 89,
        useCount: 2340,
      ),
      ExploreItemModel(
        id: '39',
        name: '印刷插画生成',
        imageUrl: '$_imageBasePath/demo39.jpg',
        likeCount: 1780,
        viewCount: 9800,
        uploadImageCount: 1,
        authorName: 'Umesh',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 17, hours: 8)),
        aspectRatio: 0.8,
        tags: ['印刷', '插画', '复古', '艺术'],
        description: '输入: 需上传一张参考图像',
        prompt: '将这张图片转换为复古印刷插画风格，使用经典的印刷技术美学',
        commentCount: 65,
        useCount: 1780,
      ),
      ExploreItemModel(
        id: '40',
        name: '超多人物姿势生成',
        imageUrl: '$_imageBasePath/demo40.jpg',
        likeCount: 3120,
        viewCount: 16800,
        uploadImageCount: 1,
        authorName: 'tapehead_Lab',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        aspectRatio: 0.6,
        tags: ['姿势', '多人物', '动作', '变化'],
        description: '输入: 需上传一张人物图像',
        prompt: '生成这个人物的多种不同姿势和动作，展示丰富的动态变化',
        commentCount: 142,
        useCount: 3120,
      ),
      ExploreItemModel(
        id: '41',
        name: '物品包装生成',
        imageUrl: '$_imageBasePath/demo41.jpg',
        likeCount: 2180,
        viewCount: 11900,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 18, hours: 12)),
        aspectRatio: 0.8,
        tags: ['包装', '产品', '设计', '商业'],
        description: '输入: 需上传一张产品图像',
        prompt: '为这个产品设计精美的包装盒，包含品牌元素和产品展示',
        commentCount: 87,
        useCount: 2180,
      ),
      ExploreItemModel(
        id: '42',
        name: '叠加滤镜/材质',
        imageUrl: '$_imageBasePath/demo42.jpg',
        likeCount: 1890,
        viewCount: 10300,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 19)),
        aspectRatio: 0.8,
        tags: ['滤镜', '材质', '叠加', '效果'],
        description: '输入: 需上传一张主图和一张材质/滤镜参考图',
        prompt: '将图2的材质/滤镜效果应用到图1上，创造独特的视觉效果',
        commentCount: 76,
        useCount: 1890,
      ),
      ExploreItemModel(
        id: '43',
        name: '控制人物脸型',
        imageUrl: '$_imageBasePath/demo43.jpg',
        likeCount: 1650,
        viewCount: 9100,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_3.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 19, hours: 6)),
        aspectRatio: 0.8,
        tags: ['脸型', '控制', '调整', '人物'],
        description: '输入: 需上传人物图像和脸型参考图',
        prompt: '调整图1中人物的脸型，使其接近图2中的脸型特征',
        commentCount: 58,
        useCount: 1650,
      ),
      ExploreItemModel(
        id: '44',
        name: '光影控制',
        imageUrl: '$_imageBasePath/demo44.jpg',
        likeCount: 2080,
        viewCount: 11400,
        uploadImageCount: 2,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_4.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        aspectRatio: 0.8,
        tags: ['光影', '控制', '照明', '效果'],
        description: '输入: 需上传主图和光影参考图',
        prompt: '根据图2的光影效果，重新为图1打光，创造戏剧性的光影效果',
        commentCount: 89,
        useCount: 2080,
      ),
      ExploreItemModel(
        id: '45',
        name: '乐高玩具小人',
        imageUrl: '$_imageBasePath/demo45.jpg',
        likeCount: 1780,
        viewCount: 9800,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_5.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 20, hours: 8)),
        aspectRatio: 0.8,
        tags: ['乐高', '玩具', '小人', '积木'],
        description: '输入: 需上传一张人物图像',
        prompt: '将这个人物制作成乐高玩具小人，包含经典的乐高积木风格和可动关节',
        commentCount: 72,
        useCount: 1780,
      ),
      ExploreItemModel(
        id: '46',
        name: '高达模型小人',
        imageUrl: '$_imageBasePath/demo46.jpg',
        likeCount: 2120,
        viewCount: 11600,
        uploadImageCount: 1,
        authorName: 'ZHO_ZHO_ZHO',
        authorAvatar: 'assets/images/demo/avatar_6.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 21)),
        aspectRatio: 0.8,
        tags: ['高达', '模型', '机甲', '小人'],
        description: '输入: 需上传一张人物图像',
        prompt: '将这个人物制作成高达模型风格的机甲驾驶员小人，包含机械细节和未来科技感',
        commentCount: 86,
        useCount: 2120,
      ),
      ExploreItemModel(
        id: '47',
        name: '硬件拆解图',
        imageUrl: '$_imageBasePath/demo47.jpg',
        likeCount: 1650,
        viewCount: 9100,
        uploadImageCount: 1,
        authorName: 'AIimagined',
        authorAvatar: 'assets/images/demo/avatar_7.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 21, hours: 12)),
        aspectRatio: 0.8,
        tags: ['硬件', '拆解', '技术', '图解'],
        description: '输入: 需上传一张电子设备图片',
        prompt: '创建这个设备的详细硬件拆解图，展示内部组件和结构',
        commentCount: 68,
        useCount: 1650,
      ),
      ExploreItemModel(
        id: '48',
        name: '食物卡路里标注',
        imageUrl: '$_imageBasePath/demo48.jpg',
        likeCount: 1340,
        viewCount: 7400,
        uploadImageCount: 1,
        authorName: 'icreatelife',
        authorAvatar: 'assets/images/demo/avatar_8.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
        aspectRatio: 0.8,
        tags: ['食物', '卡路里', '标注', '营养'],
        description: '输入: 需上传一张食物图片',
        prompt: '为这张食物图片添加详细的卡路里和营养成分标注',
        commentCount: 52,
        useCount: 1340,
      ),
      ExploreItemModel(
        id: '49',
        name: '提取信息并放置透明图层',
        imageUrl: '$_imageBasePath/demo49.jpg',
        likeCount: 1120,
        viewCount: 6200,
        uploadImageCount: 1,
        authorName: 'nglprz',
        authorAvatar: 'assets/images/demo/avatar_1.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 22, hours: 8)),
        aspectRatio: 0.8,
        tags: ['提取', '信息', '透明', '图层'],
        description: '输入: 需上传一张包含文字或信息的图片',
        prompt: '提取图片中的重要信息，并将其作为透明图层放置在新的背景上',
        commentCount: 38,
        useCount: 1120,
      ),
      ExploreItemModel(
        id: '50',
        name: '图像外扩修复',
        imageUrl: '$_imageBasePath/demo50.jpg',
        likeCount: 1890,
        viewCount: 10300,
        uploadImageCount: 1,
        authorName: 'bwabbage',
        authorAvatar: 'assets/images/demo/avatar_2.jpg',
        createdAt: DateTime.now().subtract(const Duration(days: 23)),
        aspectRatio: 0.8,
        tags: ['外扩', '修复', '扩展', '图像'],
        description: '输入: 需上传一张需要扩展的图片',
        prompt: '智能扩展这张图片的边界，自然地填充周围区域，保持风格一致',
        commentCount: 72,
        useCount: 1890,
      ),
    ];
  }
}
